name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager.yml
    secrets: inherit
  release:
    needs: [build-manager]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: manager/*.apk
